//#include "global.h"

//#include <QObject>
//#include <QMetaClassInfo>
//#include <QStringList>

//namespace QRestServer {

//QString objectKeyPropertyName(QObject *object)
//{
//    const QMetaObject *metaObject = object->metaObject();

//    int keyMetaPropertyIndex = metaObject->indexOfClassInfo(QRestServerKeyProperty);

//    Q_ASSERT_X(keyMetaPropertyIndex >= 0,
//               "QRestServer::objectKeyPropertyName",
//               QString("The class %1 has no key property.").arg(metaObject->className()).toLatin1().data());

//    return QLatin1String(metaObject->classInfo(keyMetaPropertyIndex).value());
//}

//QString objectKey(QObject *object)
//{
//    const QMetaObject *metaObject = object->metaObject();

//    int keyMetaPropertyIndex = metaObject->indexOfClassInfo(QRestServerKeyProperty);

//    Q_ASSERT_X(keyMetaPropertyIndex >= 0,
//               "QRestServer::objectKey",
//               QString("The class %1 has no key property.").arg(metaObject->className()).toLatin1().data());

//    int keyPropertyIndex = metaObject->indexOfProperty(metaObject->classInfo(keyMetaPropertyIndex).value());

//    Q_ASSERT_X(keyPropertyIndex >= 0,
//               "QRestServer::objectKey",
//               QString("The key property of class %1 does not exist.").arg(metaObject->className()).toLatin1().data());

//    QMetaProperty keyProperty = metaObject->property(keyPropertyIndex);
//    return object->property(keyProperty.name()).toString();
//}

//bool isKeyAutogenerated(QObject *object)
//{
//    const QMetaObject *metaObject = object->metaObject();

//    int keyMetaPropertyIndex = metaObject->indexOfClassInfo(QRestServerKeyAutogenerated);

//    if (keyMetaPropertyIndex <= 0)
//        return false;

//    return QVariant(metaObject->classInfo(keyMetaPropertyIndex).value()).toBool();
//}

//PropertyAttributes propertyAttributes(const char* property, QObject *object)
//{
//    const QMetaObject *metaObject = object->metaObject();

//    int classInfoIndex = metaObject->indexOfClassInfo(property);

//    if (classInfoIndex <= 0)
//        return QRestServer::NoAttributes;

//    QStringList attributeList = QString(metaObject->classInfo(classInfoIndex).value()).split(QRestServerPropertyAttributesDelimiter);

//    PropertyAttributes attributes;
//    foreach(QString attribute, attributeList) {
//        if(attribute.append(QRestServerPropertyAttributesDelimiter) ==
//                QLatin1String(QRestServerPropertyReadOnly) ) {
//            attributes |= QRestServer::ReadOnly;
//        }
//    }

//    return attributes;
//}

//QString collectionName(const QMetaObject &metaObject)
//{
//    int keyMetaPropertyIndex = metaObject.indexOfClassInfo(QRestServerCollectionName);

//    Q_ASSERT_X(keyMetaPropertyIndex >= 0,
//               "QRestServer::objectKey",
//               QString("The class %1 has no collection name.").arg(metaObject.className()).toLatin1().data());

//    return QLatin1String(metaObject.classInfo(keyMetaPropertyIndex).value());
//}

//QString collectionName(QObject *object)
//{
//    return collectionName(*object->metaObject());
//}

//} // namespace QRestServer
